# Generated by Django 4.0.5 on 2022-06-13 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_region_alter_restoran_state_delete_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_owner',
        ),
    ]
