# Generated by Django 4.0.5 on 2022-06-14 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_profile_is_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='country',
            new_name='title',
        ),
    ]
