# Generated by Django 4.0.5 on 2022-06-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_country_region_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restoran',
            name='state',
            field=models.CharField(choices=[('Mary', 'Mary'), ('Ahal', 'Ahal'), ('Balkan', 'Balkan'), ('Lebap', 'Lebap'), ('Daşoguz', 'Daşoguz'), ('Aşgabat', 'Aşgabat')], default='Mary', max_length=50),
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
