# Generated by Django 4.0.5 on 2022-06-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_restoran_state_delete_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restoran',
            old_name='state',
            new_name='region',
        ),
    ]
