# Generated by Django 4.0.5 on 2022-06-20 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_state_restoran_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restoran',
            old_name='address_line1',
            new_name='address_line',
        ),
        migrations.RenameField(
            model_name='restoran',
            old_name='mobile1',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='restoran',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='restoran',
            name='mobile2',
        ),
    ]
