# Generated by Django 4.0.5 on 2022-06-20 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_address_line1_restoran_address_line_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='food',
            name='cat_food',
        ),
        migrations.AlterField(
            model_name='food',
            name='food_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_food', to='app.category'),
        ),
        migrations.DeleteModel(
            name='Food_cat',
        ),
    ]
