# Generated by Django 4.0.5 on 2022-06-23 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_category_description_remove_food_cat_food_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_img',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
