# Generated by Django 4.0.5 on 2022-06-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_food_food_img_remove_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_image',
            field=models.ImageField(default=1, upload_to='products'),
            preserve_default=False,
        ),
    ]
