# Generated by Django 4.0.5 on 2022-06-12 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('Nobatda', 'Nobatda'), ('Ugradyldy', 'Ugradyldy'), ('Tamamlandy', 'Tamamlandy'), ('Yatyryldy', 'Yatyryldy')], default='Nobatda', max_length=50)),
                ('payment', models.CharField(choices=[('Nagt', 'Nagt'), ('Terminal', 'Terminal')], default='Nagt', max_length=15)),
                ('order_total', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ulanyjy_sargyt', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zakaz',
                'verbose_name_plural': 'Zakazlar',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sargyt_edilen', to='app.food')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sargyt_naharlar', to='root.order')),
            ],
            options={
                'verbose_name': 'Zakar Haryt',
                'verbose_name_plural': 'Zakaz Harytlar',
            },
        ),
    ]
